LADS20M3.DR4/Models/MarcaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LADS20M3.DR4.Models
{
    public class MarcaViewModel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Campo {0} deve conter entre {2} e {1} caracteres.")]
        [Display(Name = "Marca")]
        public string Nome { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Campo {0} deve conter entre {2} e {1} caracteres.")]
        [Display(Name = "País de Fundação")]
        public string PaisFundacao { get; set; }

        [Required]
        [Display(Name = "Nome do fundador")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Campo {0} deve conter entre {2} e {1} caracteres.")]
        public string NomeFundador { get; set; }

        [Required]
        [Display(Name = "Dia da fundação")]
        [DataType(DataType.Date)]
        public DateTime DiaFundacao { get; set; }

        public List<CarroViewModel> Carros { get; set; }
    }
}

LADS20M3.DR4/Controllers/CarroController.cs
using LADS20M3.DR4.HttpService;
using LADS20M3.DR4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace LADS20M3.DR4.Controllers
{
    [Authorize]
    public class CarroController : Controller
    {
        private readonly IMarcaHttpClient _marcahttpClient;
        private readonly ICarroHttpClient _carroHttpClient;

        public CarroController(
            IMarcaHttpClient marcahttpClient,
            ICarroHttpClient carroHttpClient)
        {
            _marcahttpClient = marcahttpClient;
            _carroHttpClient = carroHttpClient;
        }

        // GET: Carro
        public async Task<IActionResult> Index(string buscaTexto)
        {
            var carros = await _carroHttpClient.GetAllAsync(buscaTexto);

            ViewBag.BuscaTexto = buscaTexto;

            return View(carros.ToList());
        }

        // GET: Carro/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carroModel = await _carroHttpClient.GetByIdAsync(id.Value);
            if (carroModel == null)
            {
                return NotFound();
            }

            return View(carroModel);
        }

        // GET: Carro/Create
        public async Task<IActionResult> Create(string? buscaTexto)
        {
            var marcas = await _marcahttpClient.GetAllAsync(buscaTexto);
            ViewData["MarcaId"] = new SelectList(
                marcas,
                nameof(MarcaViewModel.Id),
                nameof(MarcaViewModel.Nome));
            return View();
        }

        // POST: Carro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MarcaCarroCreateViewModel marcaCarroCreateViewModel, string? buscaTexto)
        {
            if (ModelState.IsValid)
            {
                var marcaCarroAggViewModel = new MarcaCarroAggRequest(marcaCarroCreateViewModel);

                await _carroHttpClient.CreateAsync(marcaCarroAggViewModel);
                return RedirectToAction(nameof(Index));
            }
            var marcas = await _marcahttpClient.GetAllAsync(buscaTexto);
            ViewData["MarcaId"] = new SelectList(marcas, nameof(MarcaViewModel.Id), nameof(MarcaViewModel.Nome), marcaCarroCreateViewModel.MarcaId);
            return View(marcaCarroCreateViewModel);
        }

        // GET: Carro/Edit/5
        public async Task<IActionResult> Edit(int? id, string? buscaTexto)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carroModel = await _carroHttpClient.GetByIdAsync(id.Value);
            if (carroModel == null)
            {
                return NotFound();
            }
            var marcas = await _marcahttpClient.GetAllAsync(buscaTexto);
            ViewData["MarcaId"] = new SelectList(marcas, nameof(MarcaViewModel.Id), nameof(MarcaViewModel.Nome), carroModel.MarcaId);
            return View(carroModel);
        }

        // POST: Carro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Modelo,Ano,Portas,Cambio,Direcao,Lancamento,MarcaId")] CarroViewModel carroModel, string? buscaTexto)
        {
            if (id != carroModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _carroHttpClient.UpdateAsync(carroModel);

                return RedirectToAction(nameof(Index));
            }
            var marcas = await _marcahttpClient.GetAllAsync(buscaTexto);
            ViewData["MarcaId"] = new SelectList(marcas, nameof(MarcaViewModel.Id), nameof(MarcaViewModel.Nome), carroModel.MarcaId);
            return View(carroModel);
        }

        // GET: Carro/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carroModel = await _carroHttpClient.GetByIdAsync(id.Value);
            if (carroModel == null)
            {
                return NotFound();
            }

            return View(carroModel);
        }

        // POST: Carro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _carroHttpClient.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> CarroModelExists(int id)
        {
            return await _carroHttpClient.GetByIdAsync(id) != null;
        }

        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> CheckModelo(string modelo, int id)
        {
            if (!await _carroHttpClient.CheckModelo(modelo, id))
            {
                return Json($"Modelo {modelo} já está sendo usado.");
            }

            return Json(true);
        }
    }
}

LADS20M3.DR4/Controllers/MarcaController.cs
using LADS20M3.DR4.HttpService;
using LADS20M3.DR4.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace LADS20M3.DR4.Controllers
{
    public class MarcaController : Controller
    {
        private readonly IMarcaHttpClient _marcaHttpClient;

        public MarcaController(IMarcaHttpClient marcaHttpService)
        {
            _marcaHttpClient = marcaHttpService;
        }

        // GET: Marca
        public async Task<IActionResult> Index(string buscaTexto)
        {
            var marcas = await _marcaHttpClient.GetAllAsync(buscaTexto);

            ViewBag.BuscaTexto = buscaTexto;

            return View(marcas);
        }

        // GET: Marca/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var marcaViewModel = await _marcaHttpClient.GetByIdAsync(id.Value);

                return View(marcaViewModel);
            }
            catch (HttpRequestException e) //Quando vem um status code diferente de "Successful" (200 Ok)
            {
                Console.WriteLine(e);
                return NotFound(e.Message);
            }
            catch (NotSupportedException e) // When content type is not valid
            {
                Console.WriteLine(e);
                return NotFound(e);
            }
            catch (JsonException e) // Invalid JSON
            {
                Console.WriteLine("Invalid JSON.");
                return NotFound(e);
            }

        }

        // GET: Marca/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MarcaViewModel marcaViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var marca = await _marcaHttpClient.CreateAsync(marcaViewModel);
                    return RedirectToAction(nameof(Details), new { id = marca.Id });
                }
                catch (JsonException)
                {
                    return View("Error");
                }
            }
            return View(marcaViewModel);
        }

        // GET: Marca/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marcaViewModel = await _marcaHttpClient.GetByIdAsync(id.Value);
            if (marcaViewModel == null)
            {
                return NotFound();
            }
            return View(marcaViewModel);
        }

        // POST: Marca/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,PaisFundacao,NomeFundador,DiaFundacao")] MarcaViewModel marcaViewModel)
        {
            if (id != marcaViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _marcaHttpClient.UpdateAsync(marcaViewModel);

                return RedirectToAction(nameof(Index));
            }
            return View(marcaViewModel);
        }

        // GET: Marca/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marcaViewModel = await _marcaHttpClient.GetByIdAsync(id.Value);
            if (marcaViewModel == null)
            {
                return NotFound();
            }

            return View(marcaViewModel);
        }

        // POST: Marca/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _marcaHttpClient.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MarcaViewModelExists(int id)
        {
            var marcaEncontrada = await _marcaHttpClient.GetByIdAsync(id);
            return marcaEncontrada != null;
        }
    }
}

LADS20M3.DR4/Views/Marca/Create.cshtml
@model MarcaViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MarcaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaisFundacao" class="control-label"></label>
                <input asp-for="PaisFundacao" class="form-control" />
                <span asp-validation-for="PaisFundacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomeFundador" class="control-label"></label>
                <input asp-for="NomeFundador" class="form-control" />
                <span asp-validation-for="NomeFundador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaFundacao" class="control-label"></label>
                <input asp-for="DiaFundacao" class="form-control" />
                <span asp-validation-for="DiaFundacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LADS20M3.DR4/Views/Marca/Delete.cshtml
@model MarcaViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MarcaModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaisFundacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaisFundacao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeFundador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeFundador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiaFundacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiaFundacao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LADS20M3.DR4/Views/Marca/Details.cshtml
@model MarcaViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PaisFundacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PaisFundacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NomeFundador)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeFundador)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiaFundacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaFundacao)
        </dd>
    </dl>
    <hr />
    @if (Model.Carros.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @nameof(CarroViewModel.Modelo)
                    </th>
                    <th>
                        @nameof(CarroViewModel.Ano)
                    </th>
                    <th>
                        @nameof(CarroViewModel.Portas)
                    </th>
                    <th>
                        @nameof(CarroViewModel.Cambio)
                    </th>
                    <th>
                        @nameof(CarroViewModel.Direcao)
                    </th>
                    <th>
                        @nameof(CarroViewModel.Lancamento)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Carros)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Modelo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ano)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Portas)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cambio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Direcao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lancamento)
                        </td>
                        <td>
                            <a asp-controller="Carro" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-controller="Carro" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-controller="Carro" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    else
    {
        <p>Essa marca não possui carro cadastrado.</p>
    }

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LADS20M3.DR4/Views/Marca/Edit.cshtml
@model MarcaViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MarcaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaisFundacao" class="control-label"></label>
                <input asp-for="PaisFundacao" class="form-control" />
                <span asp-validation-for="PaisFundacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NomeFundador" class="control-label"></label>
                <input asp-for="NomeFundador" class="form-control" />
                <span asp-validation-for="NomeFundador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaFundacao" class="control-label"></label>
                <input asp-for="DiaFundacao" class="form-control" />
                <span asp-validation-for="DiaFundacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LADS20M3.DR4/Views/Marca/Index.cshtml
@model IEnumerable<MarcaViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<br />

<form asp-action="Index">
    <input type="text" name="buscaTexto" id="buscaTexto" value="@ViewBag.BuscaTexto" />
    <input type="submit" value="Search" class="btn btn-primary" />
</form>

<br />

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaisFundacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomeFundador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaFundacao)
            </th>
            <th>Quantidade</th>
            <th>Modelos</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var marcaModel in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => marcaModel.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => marcaModel.PaisFundacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => marcaModel.NomeFundador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => marcaModel.DiaFundacao)
            </td>
            <td>
                @marcaModel.Carros.Count
            </td>
            <td>
                @*recomendado usar um ViewModel e não colocar essa lógica aqui*@
                @string.Join(", ", marcaModel.Carros.Select(x => x.Modelo))
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@marcaModel.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@marcaModel.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@marcaModel.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>